message("┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓")
message("┃ 🎁 initializing CMake variables ┃")
message("┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛") 

#   build-date:
string(TIMESTAMP BUILD_DATE_YEAR "%Y")
string(TIMESTAMP BUILD_DATE_MONTH "%m")
string(TIMESTAMP BUILD_DATE_MONTH_TEXT "%b")
string(TIMESTAMP BUILD_DATE_DAY "%d")
set(BUILD_DATE "${BUILD_DATE_MONTH_TEXT} ${BUILD_DATE_DAY} ${BUILD_DATE_YEAR}")
string(TIMESTAMP BUILD_TIME_HOUR "%H")
string(TIMESTAMP BUILD_TIME_MINUTE "%M")
string(TIMESTAMP BUILD_TIME_SECOND "%S")
string(TIMESTAMP BUILD_TIME "${BUILD_TIME_HOUR}:${BUILD_TIME_MINUTE}:${BUILD_TIME_SECOND}")
set(BUILD_DATE_AND_TIME "${BUILD_DATE} ${BUILD_TIME}")

set(CXX_DEFINITIONS "${DEFINITIONS} -DUNICODE -D_UNICODE")
set(CMAKE_CXX_STANDARD 17)

set(BY_ROOT_DIR ${PROJECT_SOURCE_DIR}/..)
set(BY_MODULE_DIR ${BY_ROOT_DIR}/module)
set(BY_OUTPUT_DIR ${BY_ROOT_DIR}/bin)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BY_OUTPUT_DIR})
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BY_OUTPUT_DIR})
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${BY_OUTPUT_DIR})
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
set(CMAKE_SKIP_BUILD_RPATH FALSE)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
set(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

set(BY_POD_EXTENSION "pod")
set(BY_DEFAULT_INC_DIR
    ${BY_MODULE_DIR}
    /usr/local/include)

set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${BY_OUTPUT_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${BY_OUTPUT_DIR})
set(CMAKE_LIBRARY_PATH ${CMAKE_LIBRARY_PATH} ${CMAKE_LIBRARY_OUTPUT_DIRECTORY} /usr/local/lib)
set(BY_POD_OUTPUT_DIRECTORY ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/pod)
SET(BY_TESTDATA_SRC_PATH ${BY_MODULE_DIR}/test/testdata)
SET(BY_TESTDATA_PATH ${BY_OUTPUT_DIR}/testdata)


if ("${CMAKE_BUILD_TYPE}" STREQUAL Debug)
    set(BY_IS_DBG 1)
else ("${CMAKE_BUILD_TYPE}" STREQUAL Debug)
    set(BY_IS_DBG 0)
endif ("${CMAKE_BUILD_TYPE}" STREQUAL Debug)

